### ISSUE TITLE
Error with proxy

### ISSUE THREAD

**Issue by jjinkou2** [dopecodez/Wikipedia#39]
How can i use it with a proxy ? I have this error 

```
searchError: wikiError: FetchError: request to https://en.wikipedia.org/w/api.php?list=search&srprop=&srlimit=3&srsearch=Who%20is%20Harry%20Potter?&srinfo=suggestion&format=json&redirects=&action=query&o
rigin=*& failed, reason: connect ECONNREFUSED 185.15.58.224:443
    at AsyncFunction.wiki.search (D:\developpement\Nodejs\wikipedia\node_modules\wikipedia\dist\index.js:55:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async D:\developpement\Nodejs\wikipedia\index.js:5:31 {
  code: undefined
}
```

**Comment by dopecodez** [comment]
Could you give us the proxy for where you are seeing this error? For me with public proxies wikipedia is working fine

**Comment by dopecodez** [comment]
CLosing this issue as stale because of no new updates.
